from dataclasses import dataclass

@dataclass
class LLMTask:
    id: str  # uuid, should be generated by whoever is responsible for placing this task onto the queue
    input: str
    params: dict | None = None